version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: MySQLTestingDB
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '8001:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  gcp-storage:
    image: fsouza/fake-gcs-server
    container_name: TestGCPStorage
    restart: always
    ports:
      - '4443:4443'
volumes:
  db:
    driver: local