name: Run tests and linter

on:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # the full version of `docker-compose` command

      - name: Run tests
        run: npm run test
      
      - name: Run linter
        run: npm run lint